class_name Items

extends Node

enum ITEM_NAMES {NONE, SHOVEL, TELEPORTER_KEY, PS_CONTROLLER, CRT_TELEVISION, DIRT_HOLE, DIRT_HOLE_DUG, 
KEYCARD, KEYCARD_ULTIMATE, DOOR_KEYCARD, DOOR_LOCKED, PLAYSTATION, SEMTEX }
