class_name Items

extends Node

enum ITEM_NAMES {NONE, SHOVEL, TELEPORTER_KEY, PS_CONTROLLER, DIRT_HOLE, DIRT_HOLE_DUG, 
KEYCARD, KEYCARD_ULTIMATE, PLAYSTATION, SEMTEX }

enum INTERACTABLE_NAMES { NONE, CRT_TELEVISION, DOOR_KEYCARD, DOOR_LOCKED }